### ISSUE TITLE
Download link for mac broken

### ISSUE THREAD

**Issue by cymen** [facebook/flipper#2105]
## 🐛 Bug Report

When I go to the Flipper homepage and click the "Mac" option after Download I end up on this URL which is 404'ing:

https://www.facebook.com/fbflipper/public/mac

## To Reproduce

Go to https://www.facebook.com/fbflipper/public/mac and see 404

## Environment

Current Chrome browser on Mac

**Comment by cymen** [comment]
Actually all the download links are broken -- Linux and Windows too.

**Comment by cymen** [comment]
As a workaround, you can go to https://github.com/facebook/flipper/releases and expand Assets under v0.81.0 and there are download options for the apps.

**Comment by passy** [comment]
Thanks. Our release job failed because of the Windows build which caused all the release artifacts not to get uploaded. I'll kick off another release tomorrow once the fix is landed.

**Comment by soogong-myeonghwan** [comment]
I have same problem and got the solution here. Look forward to fixing soon.

**Comment by passy** [comment]
New release is out. Thanks for reporting!

**Comment by scarlac** [comment]
This is still an issue (the official download pages return 404). Should probably be reopened, @passy ?

**Comment by passy** [comment]
@scarlac Works for me? Can you try again?

**Comment by scarlac** [comment]
Works now! Got a 404 last time, repeatedly. Even in an incognito window. But all good now :)
