### ISSUE TITLE
OpenSSL error on iOS

### ISSUE THREAD

**Issue by iagormoraes** [facebook/flipper#2107]
## 🐛 Bug Report
The iOS app is building but it receives a SIGABRT giving to the following error:

```
dyld: Library not loaded: @rpath/OpenSSL.framework/OpenSSL
  Referenced from: /private/var/containers/Bundle/Application/6CE80915-A8A6-493A-8645-A9DAD0156E5E/limpo.app/limpo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/6CE80915-A8A6-493A-8645-A9DAD0156E5E/limpo.app/Frameworks/OpenSSL.framework/OpenSSL: mach-o, but not built for platform iOS
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```

Thus the app don't run, it keeps on a white screen.

## To Reproduce
1. Build and run the app through xcode

## Environment
- iOS 14.4.1
- Flipper 0.82.0
- Big Sur 11.2.3

**Comment by priteshrnandgaonkar** [comment]
Can you provide me with a sample app through which this error is reproducible ?

I had tried building the latest flipper code with the sample app, it works. A small repro example project will be helpful

**Comment by hsavit1** [comment]
try 

```
xcode-select --install
```

**Comment by iagormoraes** [comment]
> Can you provide me with a sample app through which this error is reproducible ?
> 
> I had tried building the latest flipper code with the sample app, it works. A small repro example project will be helpful

@priteshrnandgaonkar sorry I don't have a sample repo to provide you.

> try
> 
> ```
> xcode-select --install
> ```

@hsavit1 I reinstalled it but the same problem.


With the package `"react-native-flipper": "^0.62.0",` it works but I can't upgrade, maybe there is some other library causing conflicts to this one.

**Comment by mweststrate** [comment]
Without a reproduction there is little we can do. I recommend to verify your setup against our reference project, which works fine https://github.com/facebook/flipper/tree/master/react-native/ReactNativeFlipperExample. 

Closing the issue for now as without reproduction the issue is inactionable.

**Comment by fadlykayo** [comment]
Hi @iagormoraes , I am having exactly the same problem as yours. Did you find any solution for this?

The problem is still exist with the latest version
```
"react": "^17.0.2",
"react-native": "0.64.0"
```

**Comment by fadlykayo** [comment]
I found the solution for this (credit to: Dhavi.M):

In /ios folder
1. git clone https://github.com/krzyzanowskim/OpenSSL.git
2. cd OpenSSL
3. make
4. file -> swift packages -> add package depedency -> (project name) -> just next until finish
5. build phases ->Link binary with libraries -> add openssl.xcframework

Done!

**Comment by Jono-Chang** [comment]
Recloning my repository fixed this issue for me.

**Comment by stazrad** [comment]
This solved this for me:
1. go to xcode
2. build phases ->Link binary with libraries -> add openssl.xcframework
3. rebuild project

Good luck 🤞

**Comment by raphaelgodro** [comment]
I have the same issue. Why is this closed ? I don't see any solution provided.

**Comment by RonanMaguire1** [comment]
This is still an issue:

`Library not loaded: @rpath/OpenSSL.framework/OpenSSL`

Steps to Reproduce:

Create a react native project:
  `react-native init NewProject`

Install react-native cli globally
  `sudo npm i -g react-native-cli`

Open XCode -> Run the Project against Simulator or Real Device -> App will open and freeze with console giving following error:

`Library not loaded: @rpath/OpenSSL.framework/OpenSSL
  Referenced from: /private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/NewProject
  Reason: tried: '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/System/Library/Frameworks/OpenSSL.framework/OpenSSL' (no such file)`

Versions:

"react": "17.0.2"
"react-native": "0.67.2"
node -v: v16.13.2
nvm -v: 0.39.1
npm -v: 8.1.2

**Comment by monsef123** [comment]
> This is still an issue:
> 
> `Library not loaded: @rpath/OpenSSL.framework/OpenSSL`
> 
> Steps to Reproduce:
> 
> Create a react native project: `react-native init NewProject`
> 
> Install react-native cli globally `sudo npm i -g react-native-cli`
> 
> Open XCode -> Run the Project against Simulator or Real Device -> App will open and freeze with console giving following error:
> 
> `Library not loaded: @rpath/OpenSSL.framework/OpenSSL Referenced from: /private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/NewProject Reason: tried: '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/55E79F83-07B7-42D1-A4E7-D3538C0D1A11/NewProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/System/Library/Frameworks/OpenSSL.framework/OpenSSL' (no such file)`
> 
> Also worth noting the app crashes when `react-native run-ios` executed.
> 
> Versions:
> 
> "react": "17.0.2" "react-native": "0.67.2" node -v: v16.13.2 nvm -v: 0.39.1 npm -v: 8.1.2 MacOS: 11.6.2

Yes, still an issue.

**Comment by OmarFaruk-0x01** [comment]
> This solved this for me:
> 
>     1. go to xcode
> 
>     2. build phases ->Link binary with libraries -> add openssl.xcframework
> 
>     3. rebuild project
> 
> 
> Good luck 🤞

Thanks a lot @stazrad . It's Work For me

**Comment by miguel-lorenzo** [comment]
This is still an issue for me. Tried #[stazrad](https://github.com/stazrad) and @[monsef123](https://github.com/monsef123) solutions.

OpenSSL-Universal (1.1.1100)
npx react-native info: 

`System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 110.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by aviaot** [comment]
> ing xcode Version 14.

same for me, did you get any solution for that ?

**Comment by anuragipankaj** [comment]
@aviaot @MuhammadAbdullah54321  any idea how to fix this? please help me out also
Thank you

**Comment by wincod75** [comment]
> This solved this for me:
> 
> 1. go to xcode
> 2. build phases ->Link binary with libraries -> add openssl.xcframework
> 3. rebuild project
> 
> Good luck 🤞

This worked for me as well! No idea how or why, but without any changes what so ever to my front-end, this became an hours long battle, thanks!

**Comment by SalaarFiend** [comment]
Hello!
I had the same problem, but I solved it and told about it [here](https://medium.com/@devsalaar/dyld-library-not-loaded-error-on-ios-react-native-fix-guide-bb0b6a91e85a).
I hope this helps someone!
