### ISSUE TITLE
Flipper v0.106.0 won't launch: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2835]
## 🐛 Bug Report
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at /Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:3:2148
at loadModuleImplementation (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:2:2077)
at guardedLoadModule (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:2:1246)
at metroRequire (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:2:514)
at Object.<anonymous> (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:7:1)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
```
Incomplete screenshot below:
<img width="260" alt="Screen Shot 2021-09-08 at 10 40 44 AM" src="https://user-images.githubusercontent.com/157270/132558699-615dcdf0-e14b-47bf-ad00-baf62c537c77.png">

## To Reproduce
Launch v0.106.0. I have tried clearing out all settings storage for Flipper on my Mac, and the same occurs.

## Environment
Flipper v0.106.0
macOS 11.5.2

**Comment by anudeep3998** [comment]
👍

**Comment by mrsjlwhite** [comment]
Experiencing the same issue in the same environment. 😔

**Comment by swrobel** [comment]
Just use the thumbs-up reaction to my original post, guys. Stop spamming me with notifications

**Comment by mweststrate** [comment]
Yes noticed the same! Has been fixed in https://github.com/facebook/flipper/commit/e1e9ca0f5260f04ca41e72a17e01007f6cca4158 but needs release. In the mean time selecting a theme in the settings dialog after starting will remove the issue.

**Comment by swrobel** [comment]
@mweststrate you're actually able to launch after this error? Clicking OK does nothing, for me. I can only quit & re-launch, to the same result.

**Comment by mweststrate** [comment]
Eh yes. But alternatively, if you edit `~/.flipper/config.json` and change `darkMode: true/false` to `darkMode: "light"` it will be fixed as well. Will cut a patch release tomorrow

**Comment by swrobel** [comment]
I tried that, and the result is still the same error on launch. Perhaps this is caused by something different?
```
$ less ~/.config/flipper/settings.json | grep darkMode
  "darkMode": "light",
```

Like I'd mentioned earlier, this still occurs even when clearing out all of the Flipper settings storage (including `~/.config/flipper`) and re-launching.

**Comment by mweststrate** [comment]
I couldn't reproduce the issue anymore, 107 will land in an hour, would you mind checking whether that solves the issue?

**Comment by DoctorCobweb** [comment]
Still happening in 107, but after selecting a theme then restarting, the error went away.

**Comment by swrobel** [comment]
v107 is an improvement. Using my old (pre-106) config:
```
$ less ~/.config/flipper/settings.json | grep darkMode
  "darkMode": true,
```
I get the following on launch (although the UI does show up):
<img width="645" alt="Screen Shot 2021-09-08 at 8 31 17 PM" src="https://user-images.githubusercontent.com/157270/132617922-235f919b-2ea7-44d5-8710-8d24c8db8bbd.png">

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at IpcMainImpl.<anonymous> (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:3:3889)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
at Object.emit (events.js:315:20)
```
And I am able to at least go into the settings and change it now:
<img width="574" alt="Screen Shot 2021-09-08 at 8 31 34 PM" src="https://user-images.githubusercontent.com/157270/132617944-30f158f6-9a7c-436e-8c1b-c9acb3bc43d6.png">

As a sidenote, the Changelog hasn't been updated since v104

**Comment by mweststrate** [comment]
> Still happening in 107, but after selecting a theme then restarting, the error went away.

Ok, not what I hoped for but a bit less critical now 😅. No clue why it doesn't reproduce here, it is fairly straight forward, but will add some additional safety anyway

**Comment by DoctorCobweb** [comment]
> > Still happening in 107, but after selecting a theme then restarting, the error went away.
> 
> Ok, not what I hoped for but a bit less critical now 😅. No clue why it doesn't reproduce here, it is fairly straight forward, but will add some additional safety anyway

if it helps, i think the error msg was this second one @swrobel posted (https://github.com/facebook/flipper/issues/2835#issuecomment-915734321), not the OP version

**Comment by mweststrate** [comment]
Will release a patch in a bit.
