### ISSUE TITLE
Flipper doesn't build with Xcode "react-native": "0.70.0",

### ISSUE THREAD

**Issue by R-Kiran-Raj** [facebook/flipper#4278]
## To Reproduce

<img width="643" alt="Screenshot 2022-10-31 at 2 13 05 PM" src="https://user-images.githubusercontent.com/9262402/198967728-487bc9d7-1ca8-4320-822a-4ef65a2b45fe.png">

**Comment by Acetyld** [comment]
Exact same problem! Stuck on this for quite a while.

**Comment by Acetyld** [comment]
Downgrade to flipper 0.163.0 seems to have fixed it.

**Comment by sylv1b** [comment]
Same problem here

**Comment by TheWirv** [comment]
Seems like Xcode is trying to link Flipper again for release builds.

This had been fixed by @mweststrate a long time ago: https://github.com/facebook/flipper/issues/976#issuecomment-638957209

I wonder what happened for it to come up again. For now, my workaround has been downgrading, just like @Acetyld :/ The most recent published version (that is on npm, cocoapods, and Maven) without this bug is 0.164.0.

**Comment by BS-FastwebIT** [comment]
I was also looking for a solution for this problem, I updated to the latest version of Flipper and I was no longer able to do the building, after a while I found the solution through the Flipper site itself.

you can write this line in podfile `:flipper_configuration => FlipperConfiguration.enabled(["Debug"]),`
 ```
 .....
   permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"]),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
 .....
 ```
 
hope this can help you all :)

**Comment by TheWirv** [comment]
@BS-FastwebIT
![image](https://user-images.githubusercontent.com/4397989/199719049-c486fdc2-c402-4761-bb9b-a0807dc9a484.png)
My podfile has been looking like this ever since they introduced `FlipperConfiguration`. (Obviously, I change the version number when updating.) It doesn't change anything—at least not for versions greater than `0.164.0`.

**Comment by salmandayal** [comment]
Any solution for this issue yet?
I've tried 0.163.0 but still facing this issue when try to create in Release build in IOS

**Comment by lucasftcruz** [comment]
Same here, I can build the app locally, but any release version will fail with the error below:

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
ld: symbol(s) not found for architecture arm64`

Xcode 13.3
React Native 0.70.3
react-native-flipper 0.172.0

**Comment by sylv1b** [comment]
For me, the problem appeared after installing react-native-flipper (0.173.0).
To be able to install the app on my phone, I use this workaround, but it's not suitable for production:
`    :flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => '0.173.0' }),
`

**Comment by fjmorant** [comment]
> 

Same issue for me, I am going to try adding "Release"

**Comment by Steven-Thelin** [comment]
The same issue occurred here. I fixed this error by setting flipper version to `0.163.0` in `Podfile`:
```
:flipper_configuration => FlipperConfiguration.enabled(["Debug"], {'Flipper' => '0.163.0'}),
```


and setting `react-native-flipper` to `0.163.0` in `package.json`:

---
**However** this caused a different error:
> main.jsbundle does not exist.

I got around that by adding the following build-script to `package.json`
```
"ios:build": "react-native bundle --entry-file='index.ts' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
```
and running the above before building the app in xcode.

---
**_However..._** this now caused a different exception which I cannot get past:
```
Exception	NSException *	"\"Furya\" has not been registered.
This can happen if:\n* Metro (the local dev server) is run
from the wrong folder.
Check if Metro is running, stop it and restart it in the curr..."	0x0000600002954210
```

I've had nothing but issues with Flipper for days now, really looking for other alternatives.

**Comment by alicja99** [comment]
I downgraded flipper version to 0.163.0 without changing anything else, and it worked for me

**Comment by TheWirv** [comment]
Still an issue on the most recent 0.174.0

**Comment by iamabdulhaseeb** [comment]
@alicja99 it worked for me too, thank you. :)

**Comment by xeroxoid** [comment]
@Acetyld @alicja99 thanks that worked. Was about to completely remove Flipper as a last resort.

**Comment by YaoHuiJi** [comment]
downgrade to flipper 0.163.0 works for me with react native 0.70.2 & xcode 14.1

**Comment by JaakkoKammonen24center** [comment]
I got it working with
package.json:
"react-native": "0.70.6",
"react-native-flipper": "^0.164.0",
Podfile:
 :flipper_configuration => FlipperConfiguration.enabled(["Debug"], {'Flipper' => '0.164.0'}),
android/gradle.properties:
FLIPPER_VERSION=0.164.0

Build: 
App Center
Xcode version: 14.1
Node.js: 16.x

**Comment by cristianserban-dometic** [comment]
Same issue on my end, using `:flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.174.0' })` Any news on this one?

**Comment by longb1997** [comment]
Still happened on react-native 0.70.6 and react-native-flipper 0.176.1

**Comment by pgpankajbigstep** [comment]
@longb1997 : i have also same react-native version 0.70.6 but i solve with :flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"], {'Flipper' => '0.163.0'}),

**Comment by stereodenis** [comment]
> I got it working with package.json: "react-native": "0.70.6", "react-native-flipper": "^0.164.0", Podfile: :flipper_configuration => FlipperConfiguration.enabled(["Debug"], {'Flipper' => '0.164.0'}), android/gradle.properties: FLIPPER_VERSION=0.164.0
> 
> Build: App Center Xcode version: 14.1 Node.js: 16.x

Works for me!

**Comment by fcaldarelli** [comment]
In my case the problem was different.

Using in Podfile the default flipper configuration:

```
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"]),
```

I found that when launched `pod install --verbose` I saw that the branch version was different, in my case was 1.76.0.1.9. The 1.76.0.1.9 missed *asm* folder needed to link the code.

In the screen I put the right version.

<img width="1566" alt="Screenshot 2023-01-20 alle 10 46 28" src="https://user-images.githubusercontent.com/4108673/213666119-b896fbf7-945a-4103-a531-c6befa6c802a.png">


To fix, call `pod repo list` and update the CDN (usually named as trunk) with

`pod repo update trunk` (if at your side is named trunk)

Launch again `pod install --verbose` and you will see the same and right version of the Pod.

**Comment by HugoGresse** [comment]
Same issue using `"react-native-flipper": "^0.189.0",` with RN 0.70.8 

Reverting to `0.163.0`, `npm i`, `pod install` fixed the issue.

**Comment by fondue-tech** [comment]
When there are issues in my rn apps it's always flipper, I have tried all fixes mentioned above and nothing works.

**Comment by fukemy** [comment]
any solution please, Im feel much tied and painful when upgrade react native to 0.71.x

**Comment by pgy108103** [comment]
> just set `:flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"]),`
> 
> work to me, nothing to do

@fukemy thank you!!  it works for me

**Comment by raphaelinmanage** [comment]
> Same issue using `"react-native-flipper": "^0.189.0",` with RN 0.70.8
> 
> Reverting to `0.163.0`, `npm i`, `pod install` fixed the issue.

Hey, i have the same problem with flipper 0.189.0 
i downgraded to 0.163.0 and works fine
Any update on the latest version?

**Comment by Nensi9** [comment]
I have the same problem with flipper 0.192.0
I downgraded it to 0.163.0 and works perfectly.
Not working with the latest version 0.201.0 also.
Any update on the latest version?

**Comment by mManishTrivedi** [comment]
We also encountered this issue and spent almost two days investigating it. We eventually discovered that the versions of the `package.json` and `Podfile` files were different. After updating both files to flipper 0.163.0, the issue was resolved. (This was for React Native 0.71.0.)

**Comment by ark-app-admin** [comment]
> just set `:flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"]),`
> 
> work to me, nothing to do

This enables flipper for your release build, which is not something you want to do

**Comment by npinney** [comment]
Having this issue regardless of version and regardless of adding `"Release"` or not. I am using react native 0.71. Can anyone share a patch package or post_install script to remove `FB_SONARKIT_ENABLED=1` from FlipperKit pod build settings? Using Bitrise and until (or if ever) @leotm commit is merged, I see no way to get around this other than removing flipper altogether 🤦‍♂️😒

**Comment by cam-shaw** [comment]
@npinney you should be able to add `NO_FLIPPER=1` as an environment variable in Bitrise.
In your Podfile, it should look for NO_FLIPPER 
e.g.

```ruby
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
```

**Comment by esbenvb** [comment]
In my case, this was solved by installing the proper version of the `react-native-flipper` npm package.

I could see in the `Podfile.lock` and `gradle.properties` the binary Flipper version was 0.125.0 so I did a `yarn add react-native-flipper@0.125.0` instead of the default version, and now I can build again :)

**Comment by recallwei** [comment]
Still not or, "react-native": "0.72.5", "react-native-flipper": "0.212.0"

**Comment by fimak** [comment]
in Pods file
`:flipper_configuration => FlipperConfiguration.enabled(["Debug"]),`

in recat-native.config.js
```
module.exports = {
  dependencies: {
    'react-native-flipper': {
      platforms: {
        ios: null,
      },
    },
  },
...
};
```

then do `pod install`

**Comment by ceres-quangd** [comment]
Just wondering if there is any update on this issue or newer version of Flipper 163.

**Comment by fcaldarelli** [comment]
It might no longer be an issue since the use of Flipper is discouraged from version 0.73 onwards.

https://github.com/react-native-community/discussions-and-proposals/pull/641

**Comment by minnat65** [comment]
> in Pods file `:flipper_configuration => FlipperConfiguration.enabled(["Debug"]),`
> 
> in recat-native.config.js
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-flipper': {
>       platforms: {
>         ios: null,
>       },
>     },
>   },
> ...
> };
> ```
> 
> then do `pod install`

I also ran into the same bug but fortunately, this solution worked for me.
