### ISSUE TITLE
FlipperKit cocoapod versions missing for latest releases (0.176.0 & 0.176.1)

### ISSUE THREAD

**Issue by liamjones** [facebook/flipper#4382]
## 🐛 Bug Report

I was following the docs to update an RN app to use the latest version of Flipper: https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk

The docs list 0.176.1 in the instructions as the latest version, which is correct. However, while the maven artifact exists for 0.176.1, the FlipperKit cocoapod does not: https://cocoapods.org/pods/FlipperKit

## To Reproduce
Set Flipper to 0.176.1 in an RN project:
```ruby
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.176.1' }),
```

## Environment
RN 0.69.7
Flipper 0.176.1

**Comment by Gerlison** [comment]
![image](https://user-images.githubusercontent.com/28146931/208932458-0e930309-78db-4955-898e-17af12fab968.png)
In the doc you linked, says that React Native >= 0.69 Flipper version has to be 0.159.0

**Comment by liamjones** [comment]
@Gerlison Wait... You can only use the *newest* versions of flipper (e.g. 0.176.1) on *older* react-native (less than 0.69.0)? 😕

**Comment by liamjones** [comment]
This also seems to disagree with the statement above it on that page:

> Latest version of Flipper requires react-native 0.69+! If you use react-native < 0.69.0, please, downgrade react-native-flipper to 0.162.0 (see [this GitHub issue](https://github.com/facebook/flipper/issues/4240) for details).

**Comment by Gerlison** [comment]
@liamjones I just tried to install the newest version (0.176.1) on my project. Updated package.json and Podfile to that version. When I tried to `pod install --repo-update`, I got the same error as yours. Then, I downgraded Podfile version to the version indicated on the screenshot I sent you, but kept the latest on Android and package.json.
![image](https://user-images.githubusercontent.com/28146931/208941043-5b1dbb4a-058b-480e-833c-06c866ce14ef.png)

Didnt build the ios to try it yet, actualy. But solved the issue of installing the pods for me.

**Comment by markholland** [comment]
Seeing the same problem. Sticking with 0.175.0

**Comment by kepop1** [comment]
Same issue on my side. Running React Native 0.70.6 and Flipper 0.176.1 for iOS / Android. Android runs fine, no warnings, but iOS has the warning even with running the usual `pod install --repo-update` etc. This is with a fresh Podfile.lock being generated as well. 

I wonder why https://cocoapods.org/pods/FlipperKit doesn't have the 0.176.1 version pushed to it?

Copy of the warning:
```
The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory.
```

For what it's worth, Flipper still works fine despite the warning 🤷

**Comment by Gerlison** [comment]
@markholland  @kepop1 Despite this is only a warning and android is working fine, I faced some errors on iOS when using a version greater than 0.159.0. The main problem was the Network plugin. It stopped working on iOS. After I downgraded back to 0.159.0, the plugin was fixed.

If that doesn't apply to your projetcts, it's fine then. :)

**Comment by lundn** [comment]
Any updates on this? Are are latest supported version of Flipper for React-Native v.0.159.0?

**Comment by nicode-io** [comment]
Same issue for me, 0.176.0 is founded by Cocoapods but not the most recent updates

**Comment by notjosh** [comment]
The CocoaPods publishing has failed for the last few versions ([here](https://github.com/facebook/flipper/actions/workflows/publish-pods.yml)), each of them after six (!) hours of trying.

**Comment by adamsinnott** [comment]
This is still an issue. There is no documentation showing this and finding why its not working is tricky and time consuming. Additionally 0.176.0 is not present. The latest package present is 0.175.0.

**Comment by adamsinnott** [comment]
Was a header removed by mistake? 

`ERROR | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  FlipperKit/iOS/Plugins/FlipperKitLayoutPlugin/FlipperKitLayoutComponentKitSupport/SKComponentLayoutWrapper.mm:27:8: error: cannot find protocol declaration for 'RCMountable'; did you mean 'CKMountable'?`

`2023-02-10T23:54:53.9023160Z     - ERROR | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild: Returned an unsuccessful exit code.
2023-02-10T23:54:53.9024210Z     - NOTE  | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'RenderCore' from project 'Pods')
2023-02-10T23:54:53.9025190Z     - WARN  | [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  Headers/Private/RenderCore/CKVariant.h:354:9: warning: parameter '_' not found in the function declaration [-Wdocumentation]
2023-02-10T23:54:53.9026240Z     - ERROR | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  FlipperKit/iOS/Plugins/FlipperKitLayoutPlugin/FlipperKitLayoutComponentKitSupport/SKComponentLayoutWrapper.mm:26:8: error: cannot find protocol declaration for 'RCMountable'; did you mean 'CKMountable'?
2023-02-10T23:54:53.9027200Z     - NOTE  | [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  Headers/Private/ComponentKit/CKAnalyticsListener.h:23:11: note: 'CKMountable' declared here
2023-02-10T23:54:53.9028230Z     - ERROR | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  FlipperKit/iOS/Plugins/FlipperKitLayoutPlugin/FlipperKitLayoutComponentKitSupport/SKComponentLayoutWrapper.mm:27:8: error: cannot find protocol declaration for 'RCMountable'; did you mean 'CKMountable'?
2023-02-10T23:54:53.9029410Z     - NOTE  | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'ComponentKit' from project 'Pods')
2023-02-10T23:54:53.9030490Z     - NOTE  | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  warning: no rule to process file 'ComponentKit/ComponentKit/ComponentKit.xcconfig' of type 'text.xcconfig' for architecture 'arm64' (in target 'ComponentKit' from project 'Pods')
2023-02-10T23:54:53.9031540Z     - NOTE  | [iOS] [FlipperKit/FlipperKitLayoutComponentKitSupport] xcodebuild:  warning: no rule to process file 'ComponentKit/ComponentKit/ComponentKit.xcconfig' of type 'text.xcconfig' for architecture 'x86_64' (in target 'ComponentKit' from project 'Pods')
2023-02-10T23:54:53.9032390Z     - WARN  | [FlipperKit/FlipperKitExamplePlugin,FlipperKit/FlipperKitReactPlugin] file patterns: The `public_header_files` pattern did not match any file.`

**Comment by lblasa** [comment]
Sorry about this, looking into it now.

**Comment by lblasa** [comment]
Problem has been identified, a fix will be provided very shortly.

**Comment by adamsinnott** [comment]
Fantastic thank you

**Comment by Rohindh-R** [comment]
Still facing the same issue in 0.190.0

**Comment by therealkh** [comment]
the same here for 1.190.0

**Comment by williamwa** [comment]
same problem 0.190.0

**Comment by miguelherz** [comment]
Version 0.191.0 was just released 2 hours ago.. but same issue with the pods.. it failed to publish flipper pod

**Comment by soulei-dev** [comment]
> the same here for 0.190.0

same

**Comment by lethanhan97** [comment]
the same here for both 0.190.0 and 0.238.0. React-native version 0.70.13

**Comment by VittoriDavide** [comment]
someone still facing this with 0.201 ?

**Comment by ankitbajpai1607** [comment]
yes


> someone still facing this with 0.201 ?

yes

**Comment by deepen168** [comment]
Is there any updates or workaround for this? I am starting out with RN and stuck on this error. would really apreciate help. Thanks!

**Comment by paulopgss** [comment]
After updating my xcode I had the same problem using version 0.125.0. Searching other topics, I found one that worked for me, I hope it helps:

[#43335](https://github.com/facebook/react-native/issues/43335#issuecomment-1980246463)

**Comment by eusouoviana** [comment]
This still happens to me

**Comment by mobinahmed** [comment]
I had the same issue with 0.201, you can try updating your pods. This resolved issue for me
~> pod update (under ios folder)
Mac OS M1 Sonoma 14.3.1
Xcode 15.3
React-Native 0.73.5

Flipper deprecated moving forward 
https://github.com/react-native-community/discussions-and-proposals/pull/641

**Comment by sachittt** [comment]
I was also facing same issue since yesterday. Finally able to resolve it.
I was able to find temp fix with adding #include <functional> to ios/Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h
may be an flipper needs an upgrade.

**Comment by stargt** [comment]
Same here. I finally applied the temp fix as @sachittt did.


Check also:

- https://github.com/facebook/flipper/commit/b3dcdb87f930dbbc9dbacb53ad60996e0111e7d8
- https://github.com/facebook/flipper/issues/5500#issuecomment-1980567597
- https://github.com/facebook/react-native/issues/43335#issuecomment-1982794252

**Comment by Gopinath-22-PS** [comment]
> <img alt="Screenshot 2024-03-08 at 4 26 45 PM" width="1440" src="https://private-user-images.githubusercontent.com/39151342/311209833-76479948-fa91-46db-af8b-87afe9c45c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDg2NjgsIm5iZiI6MTcxMDI0ODM2OCwicGF0aCI6Ii8zOTE1MTM0Mi8zMTEyMDk4MzMtNzY0Nzk5NDgtZmE5MS00NmRiLWFmOGItODdhZmU5YzQ1Yzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEyNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDAyYmUzMWRmOWE2ZmVhZWMwZmQ4ZWI5MmQyZDJmZGI5YWMzZTliY2ExZGUyMWZkMTllZTVlY2NhNGJiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ED9zrwjbyvTFg8plahALG7KdSOmrWvbzSj4QnI66lFU"> I was also facing same issue since yesterday. Finally able to resolve it.
> I was able to find temp fix with adding #include to ios/Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h may be an flipper needs an upgrade.

@sachittt , You saved my time!

**Comment by Gopinath-22-PS** [comment]
> Same here. I finally applied the temp fix as @sachittt did.
> 
> Check also:
> 
> * [b3dcdb8](https://github.com/facebook/flipper/commit/b3dcdb87f930dbbc9dbacb53ad60996e0111e7d8)
> * [macos 14.3.1 xcode 15.3 'facebook::flipper::SocketCertificateProvider' (aka 'int') is not a function or function pointer #5500 (comment)](https://github.com/facebook/flipper/issues/5500#issuecomment-1980567597)
> * [[Has Workaround] Upgrading Xcode to 15.3 results in build error - `Called object type 'facebook::flipper::SocketCertificateProvider' (aka 'int') is not a function or function pointer` react-native#43335 (comment)](https://github.com/facebook/react-native/issues/43335#issuecomment-1982794252)

@stargt , I tried but none of them is working.

**Comment by stargt** [comment]
@Gopinath-22-PS Yeah, it was my misunderstanding, I've finally disabled Flipper after I found an article that says Flipper is about to be deprecated.

**Comment by abhibhat33** [comment]
> <img alt="Screenshot 2024-03-08 at 4 26 45 PM" width="1440" src="https://private-user-images.githubusercontent.com/39151342/311209833-76479948-fa91-46db-af8b-87afe9c45c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTgzOTMsIm5iZiI6MTcxMDM5ODA5MywicGF0aCI6Ii8zOTE1MTM0Mi8zMTEyMDk4MzMtNzY0Nzk5NDgtZmE5MS00NmRiLWFmOGItODdhZmU5YzQ1Yzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA2MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTE1Y2FlNmU5NTBlMDY0YzQ2MzdiOWI5ZjJhZjRkMzQ2MWNlZjIwOTc1MDNmOWQ0OGNkMzBlNGYyMGNhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8KKKM4stWrney5ibjogPHA2_J6DPVoL4knZN6WU4XfA"> I was also facing same issue since yesterday. Finally able to resolve it.
> I was able to find temp fix with adding #include to ios/Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h may be an flipper needs an upgrade.

Yeah, thanks @sachittt it's working fine. Is this issue fixed in new RN version?

**Comment by liamjones** [comment]
@abhibhat33 Looks like it's fixed in these versions:
* https://github.com/facebook/react-native/releases/tag/v0.73.6
* https://github.com/facebook/react-native/releases/tag/v0.72.12
