### ISSUE TITLE
FlipperOkHttpInterceptor blocks multipart/form-data requests

### ISSUE THREAD

**Issue by aDavidaIsNoOne** [facebook/flipper#993]
## 🐛 Bug Report
Network plugin is blocking multipart/form-data requests.

## To Reproduce
  See: facebook/react-native#28551
## Environment
React Native 0.62.0
flipper-network-plugin 0.33.1

**Comment by passy** [comment]
This appears to be happening only on Android based on the upstream report. Thanks for flagging!

**Comment by cekkaewnumchai** [comment]
I tried to repro directly from our sample app with similar request, but it seems this worked fine.

I will try to repro from React Native app directly.
![Screenshot 2020-04-14 at 11 57 08](https://user-images.githubusercontent.com/18430703/79217998-a38e2100-7e47-11ea-8c0e-7fef17e94d2f.png)

**Comment by omerman** [comment]
@cekkaewnumchai 
You are welcome to use my repro repo :)

https://github.com/omerman/React-native-android-upload-file-errors

**Comment by cekkaewnumchai** [comment]
Closed.

The fix has landed in master

**Comment by cekkaewnumchai** [comment]
Closed

**Comment by aprilmintacpineda** [comment]
Has the fix been released? How do we upgrade?

**Comment by cekkaewnumchai** [comment]
This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `

```gradle
27    # Version of flipper SDK to use with React Native
28    FLIPPER_VERSION=0.39.0  // edit this manually
```

**Comment by aprilmintacpineda** [comment]
Thanks so much for your kindness @cekkaewnumchai!

**Comment by tezka003** [comment]
> This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> 
> ```groovy-gradle
> 27  # Version of flipper SDK to use with React Native
> 28  FLIPPER_VERSION=0.39.0  // edit this manually
> ```

Hi sir changing the FLIPPER_VERSION gives me a build failed output

**Comment by kuldeepworkid** [comment]
still facing network issue in
 react-native='62.2'
FLIPPER_VERSION=0.39.0

**Comment by MahmonirB** [comment]
I had this problem and solve it via commenting the 43 line in android/src/debug/.../.../ReactNativeFlipper.java

`// builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));`
could you test it?

**Comment by siddhantbhatia** [comment]
> This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> 
> ```groovy-gradle
> 27  # Version of flipper SDK to use with React Native
> 28  FLIPPER_VERSION=0.39.0  // edit this manually
> ```

Thank you! This worked for me

**Comment by mauricioblum** [comment]
> > This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> > ```
> > 27  # Version of flipper SDK to use with React Native
> > 28  FLIPPER_VERSION=0.39.0  // edit this manually
> > ```
> 
> Thank you! This worked for me

Worked for me too! Thanks!!

**Comment by JonatanOrtiz** [comment]
I tried it all, it didn't work.

**Comment by Baterka** [comment]
Not work for me as well:
FLIPPER_VERSION=0.39.0
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-flipper": "^0.39.0",

**Comment by SittisukChartrasee** [comment]
> > This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> > ```
> > 27  # Version of flipper SDK to use with React Native
> > 28  FLIPPER_VERSION=0.39.0  // edit this manually
> > ```
> 
> Thank you! This worked for me

What your use react native version?

**Comment by mweststrate** [comment]
Closing as the fix has landed

**Comment by joelpiccoli** [comment]
> This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> 
> ```groovy-gradle
> 27  # Version of flipper SDK to use with React Native
> 28  FLIPPER_VERSION=0.39.0  // edit this manually
> ```

You are a life saver man! Thank you so much! s2 s2 s2 s2

**Comment by FaycalBorsali** [comment]
> This should be fixed in version 0.39.0. To upgrade, edit `android > gradle.properties `
> 
> ```groovy-gradle
> 27  # Version of flipper SDK to use with React Native
> 28  FLIPPER_VERSION=0.39.0  // edit this manually
> ```

Thank you you are a life saver !

PS: if anyone still has a problem, I had to clean the android project `cd android && ./gradlew clean && cd ..` for the change to take effect

**Comment by surajl11** [comment]
did it ,its not because of the flipper version ,I'm using react -native 0.62.2 and flipper version :0.33.1,commented out line 43 in android/app/src/debug/java/com/maxyride/app/drivers/ReactNativeFlipper.java and made sure the type in upload is specified properly,

**Comment by RupamShaw** [comment]
I resolved network issue in android in fomdata append uri with file:// 
```
formData.append(`video${idx}`, {
            name: img.name,
            type: `video/${ext}`,
            uri: `file://${img.sourceURL}`,
          })
```

**Comment by Aurangempire** [comment]
STILL FACING THE SAME ISSUE :((( 

# Version of flipper SDK to use with React Native
FLIPPER_VERSION=0.54.0

**Comment by mweststrate** [comment]
@Aurangempire this issue is closed and the current Flipper version is 0.80. So please file fresh issues on recent versions and follow the template by providing a minimal reproduction so that your issue becomes actionable. We won't be landing fixes on a year old Flipper version and using all caps won't change that.
